### ISSUE TITLE
Receiving 404 on start

### ISSUE THREAD

**Issue by Hoversquid** [CubieDev/TwitchAIDungeon#1]
The program doesn't seem to be able to connect to the server. Is this a bug or has the API changed since this was made?
Thanks.

**Comment by tomaarsen** [comment]
Hello @Hoversquid 

I'm afraid the API has seen severe changes since this program was written. 
The entire system that AI Dungeon 2 uses to send data from the server to the frontend has changed entirely, and patching these changes will take a lot of time and effort. Sadly, I can't prioritize this project right now.

I'll update the README to specify that this project no longer works, and am open to fixes.

Perhaps I'll have time to revisit this project in the future.

I appreciate the issue, and am sorry that I can only report bad news.

- Tom Aarsen
